spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/weixin?verifyServerCertificate=false&useSSL=true
    username: qiao
    password: qiao
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
server:
  port: 80